Release 3.2.4
kgpmask/MASK pull request #150
Opened 2023-05-28 08:31 UTC by Goose-Of-War

Newsletter crossword and compression

2023-05-28 08:33 UTC, Goose-Of-War commented
#150 Yay 🥳🥳

2023-05-28 08:41 UTC, nishkalprakash requested changes

2023-05-28 08:41 UTC, nishkalprakash commented on templates/newsletters/2023-05-1/2023-05-1.njk
The crossword scroll isnt loading

2023-05-28 08:41 UTC, nishkalprakash commented on templates/newsletters/2023-05-1/2023-05-1.njk
![image](https://github.com/kgpmask/MASK/assets/42577624/1f8bc545-17af-479f-8712-665bd6d4129c)

2023-05-28 08:41 UTC, nishkalprakash commented on templates/newsletters/2023-05-1/2023-05-1.njk
checked in mobile screen as well

2023-05-28 10:29 UTC, Goose-Of-War commented on templates/newsletters/2023-05-1/2023-05-1.njk
Workin on it

2023-05-28 11:38 UTC, nishkalprakash approved these changes

2023-05-28 12:13 UTC, merged

2023-06-06 09:20 UTC, nishkalprakash reviewed
good work