adding bidoof event article
kgpmask/MASK pull request #272
Opened 2024-12-02 13:43 UTC by uday-kalyan-s

adding the bidoof event article.

- [x] made entry in py_events
- [x] added route
- [x] made event page\
- [x] added needed assets

2024-12-02 13:49 UTC, wildcraft958 commented
Everything seems fine

2024-12-03 17:50 UTC, ItsAnkan requested changes

2024-12-03 17:50 UTC, ItsAnkan commented on templates/event-articles/bidoof-art.njk
> +	<h2> declaration </h2>
Title Case

2024-12-03 17:50 UTC, ItsAnkan commented on templates/event-articles/bidoof-art.njk
> +	<h2> results </h2>
"Results"

2024-12-03 17:50 UTC, ItsAnkan commented on assets/events/bidoof-art.jpg
its too large, try to make it a bit smaller by compressing it

2024-12-04 13:06 UTC, destryptor approved these changes

2024-12-04 13:21 UTC, ItsAnkan approved these changes
approved

2024-12-04 13:22 UTC, destryptor commented
Merging, blame onkon if anything breaks (free trit automatically)

2024-12-04 13:22 UTC, merged