" Your name " screening event article
kgpmask/MASK pull request #273
Opened 2024-12-02 14:59 UTC by Aryansinghparmar

2024-12-02 15:20 UTC, wildcraft958 commented on templates/submissions.njk
why validator is here??

2024-12-02 15:25 UTC, wildcraft958 commented on npm-shrinkwrap.json
@ItsAnkan @destryptor  help!!

2024-12-03 17:56 UTC, ItsAnkan requested changes

2024-12-03 17:56 UTC, ItsAnkan commented on package.json
shouldn't be here

2024-12-03 17:56 UTC, ItsAnkan commented on templates/submissions.njk
remove validators

2024-12-04 12:41 UTC, ItsAnkan requested changes
I told you to remove the changes from package.json, not remove package.json ;-;

2024-12-04 13:56 UTC, ItsAnkan approved these changes
Approved

2024-12-04 13:57 UTC, merged