ocaq-2024
kgpmask/MASK pull request #274
Opened 2024-12-02 16:26 UTC by Ajayendra2705

2024-12-02 16:44 UTC, wildcraft958 commented
@ItsAnkan merge conflict ;-;

2024-12-03 18:02 UTC, ItsAnkan requested changes

2024-12-03 18:02 UTC, ItsAnkan commented on templates/event-articles/py_events.njk
> +		{{ event (
move this to the top before OCAQ 2023, these will be displayed by the order you arrange here, and we want the lates ones first, so...

2024-12-04 13:44 UTC, ItsAnkan approved these changes
Approved

2024-12-04 13:48 UTC, merged